name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      name: Checkout
      uses: actions/checkout@v3
      run: |
        npm run test
        npm run build
      name: Setup Pages
      working-directory: ./build
      uses: actions/configure-pages@v3
      name: Deploy to GitHub Pages
      working-directory: ./build
      uses: actions/deploy-pages@v1
